version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "book-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vqnwbwhf2tew"
s3_prefix = "book-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
